name: Create PR
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'target commit hash'
        required: false
        type: string
  push:
    branches:
      - 'dev-kakurega'
    paths:
      - 'package.json'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: check tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check pr exists
        id: check-pr
        run: |
          echo "Checking PR exists"

          echo "Using repository: ${{ github.repository }}"
          gh repo set-default ${{ github.repository }}

          COUNT=$(gh pr list -S 'release in:title' --json title --jq '.[].title' | grep '${{ steps.package-version.outputs.current-version }}' | wc -l)
          if [ $((COUNT)) -gt 0 ]; then
              echo "exists=true" >> $GITHUB_OUTPUT
              echo "PR already exists"
          else
              echo "exists=false" >> $GITHUB_OUTPUT
              echo "PR does not exist"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        if: steps.check-tag.outputs.exists == 'false' && steps.check-pr.outputs.exists == 'false'
        run: |
          if [ -z "${{ inputs.tags }}" ]; then
            TAG=$(git rev-parse HEAD)
          fi

          echo "Creating PR"
          GH_COMMAND='gh pr create -B "master-kakurega" -H "dev-kakurega" -t "release: v${{ steps.package-version.outputs.current-version }}" -b "Automated pr by github actions"'

          if git log $TAG -1 --pretty=%B | grep "^Merge tag '.+-(alpha|beta|rc).+'"; then
            $GH_COMMAND --draft
          else
            $GH_COMMAND
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ inputs.tags }}
