name: Create release tag

on:
  workflow_dispatch:
  push:
    branches:
      - 'master-kakurega'
    paths:
      - 'package.json'

jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: check tag exists
        uses: mukunku/tag-exists-action@v1.4.0
        id: check-tag
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create tag
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git tag -a v${{ steps.package-version.outputs.current-version }} -m "release: v${{ steps.package-version.outputs.current-version }}"
          git push origin v${{ steps.package-version.outputs.current-version }}
