name: PR latest version check
on:
  pull_request:
    types: [synchronize]

jobs:
  check-latest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: check version
        id: check-version
        run: |
          echo "Check if the version name has changed"

          echo "Using repository: ${{ github.repository }}"
          gh repo set-default ${{ github.repository }}

          MISSKEY_VERSION=$(echo '${{ steps.package-version.outputs.current-version }}' | cut -d '-' -f 1)
          COUNT=$(gh pr view ${{ github.event.number }} --json title --jq '.title' | grep $MISSKEY_VERSION | wc -l)
          if [ $((COUNT)) -gt 0 ]; then
              echo "exists=true" >> $GITHUB_OUTPUT
              echo "Version already exists"
          else
              echo "exists=false" >> $GITHUB_OUTPUT
              echo "Version does not exist"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: update pr
        if: steps.check-version.outputs.exists == 'false'
        shell: bash
        run: |
          gh pr edit ${{ github.event.number }} -t "release: v${{ steps.package-version.outputs.current-version }}"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
